version: '3.8'

services:

  cf_ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    environment:
      PUID: 1000
      PGID: 1000
      CF_DDNS_API_TOKEN: "${CF_DDNS_API_TOKEN}"
      CF_DDNS_API_KEY: "${CF_DDNS_API_KEY}"
      CF_DDNS_ACCOUNT_EMAIL: "${CF_DDNS_ACCOUNT_EMAIL}"
      CF_DDNS_ZONE_ID: "${CF_DDNS_ZONE_ID}"
      CF_DDNS_SUBDOMAIN: "${CF_DDNS_SUBDOMAIN}"
    volumes:
      - ./conf/ddns/config.json:/config.json
    restart: always

  # traefik:

  # oauth_proxy:

